/** v6 display tiers (phone). */
export const PEDIGREE_CARD_BIG_W = 96;
export const PEDIGREE_CARD_BIG_H = 64;
export const PEDIGREE_CARD_SMALL_W = 72;
export const PEDIGREE_CARD_SMALL_H = 50;

/** Legacy default card (payload fallback). */
export const PEDIGREE_CARD_W = PEDIGREE_CARD_SMALL_W;
export const PEDIGREE_CARD_H = PEDIGREE_CARD_SMALL_H;

export const PEDIGREE_FOCAL_COUPLE_GAP = 48;
export const PEDIGREE_COUPLE_GAP = PEDIGREE_FOCAL_COUPLE_GAP;
export const PEDIGREE_GENERATION_GAP = 80;
export const PEDIGREE_STEM_CLEARANCE = 32;
export const PEDIGREE_CONNECTOR_STROKE = 4;
export const PEDIGREE_SPOUSE_BAR = 5;
export const PEDIGREE_MIN_L_JOG = 16;
export const PEDIGREE_CHEVRON_OFFSET = 8;
export const PEDIGREE_PARENT_OUTER_MARGIN = 20;
export const PEDIGREE_PARENT_MID_GAP = 64;
export const PEDIGREE_EDGE_INSET = 8;

/** v7 connector colors */
export const PEDIGREE_COLOR_PARENT = "#E6B428";
export const PEDIGREE_COLOR_SPOUSE = "#C83C3C";
export const PEDIGREE_COLOR_CHILD = "#328C50";
export const PEDIGREE_COLOR_SIBLING = "#326EBE";
export const PEDIGREE_COLOR_PATH = "#7828A0";

export const PEDIGREE_COLUMN_STEP = PEDIGREE_CARD_SMALL_W + PEDIGREE_MIN_L_JOG;
export const PEDIGREE_COUPLE_OFFSET = PEDIGREE_CARD_BIG_W + PEDIGREE_FOCAL_COUPLE_GAP;
export const PEDIGREE_ROW_STEP = PEDIGREE_CARD_BIG_H + PEDIGREE_GENERATION_GAP;
