import type { DemoDataset, DemoDatasetStats } from "./types";

/**
 * Three-generation Hassan–Khan pedigree with siblings on both partner wings,
 * parents above each spouse, and children below the focal union.
 * Used for onboarding / sample data where every relation must be navigable on the tree map.
 */
export function buildCuratedPedigreeDemo(): DemoDataset {
  const persons = [
    {
      id: "cur-omar",
      firstName: "Omar",
      lastName: "Hassan",
      gender: "MALE" as const,
      birthDate: "1934-03-12",
      deathDate: "2010-08-01",
      currentCity: "Lahore",
    },
    {
      id: "cur-fatima",
      firstName: "Fatima",
      lastName: "Khan",
      gender: "FEMALE" as const,
      birthDate: "1938-11-02",
      deathDate: "2018-04-19",
      currentCity: "Lahore",
    },
    {
      id: "cur-rashid",
      firstName: "Rashid",
      lastName: "Hassan",
      gender: "MALE" as const,
      birthDate: "1960-06-20",
      deathDate: "2019-01-15",
      currentCity: "Karachi",
    },
    {
      id: "cur-nadia",
      firstName: "Nadia",
      lastName: "Hassan",
      gender: "FEMALE" as const,
      birthDate: "1964-02-08",
      deathDate: null,
      currentCity: "Karachi",
    },
    {
      id: "cur-margaret",
      firstName: "Margaret",
      lastName: "Khan",
      gender: "FEMALE" as const,
      birthDate: "1962-09-30",
      deathDate: null,
      currentCity: "London",
    },
    {
      id: "cur-kay",
      firstName: "Kay",
      lastName: "Hassan",
      gender: "MALE" as const,
      birthDate: "1990-07-14",
      deathDate: null,
      currentCity: "London",
    },
    {
      id: "cur-emma",
      firstName: "Emma",
      lastName: "Khan",
      gender: "FEMALE" as const,
      birthDate: "1992-01-22",
      deathDate: null,
      currentCity: "London",
    },
    {
      id: "cur-ali",
      firstName: "Ali",
      lastName: "Khan",
      gender: "MALE" as const,
      birthDate: "1994-05-03",
      deathDate: null,
      currentCity: "Dubai",
    },
    {
      id: "cur-sara",
      firstName: "Sara",
      lastName: "Khan",
      gender: "FEMALE" as const,
      birthDate: "1996-12-11",
      deathDate: null,
      currentCity: "Lahore",
    },
    {
      id: "cur-aisha",
      firstName: "Aisha",
      lastName: "Rahman",
      gender: "FEMALE" as const,
      birthDate: "1991-04-18",
      deathDate: null,
      currentCity: "London",
    },
    {
      id: "cur-yusuf",
      firstName: "Yusuf",
      lastName: "Rahman",
      gender: "MALE" as const,
      birthDate: "1988-10-05",
      deathDate: null,
      currentCity: "Birmingham",
    },
    {
      id: "cur-hasan-rahman",
      firstName: "Hasan",
      lastName: "Rahman",
      gender: "MALE" as const,
      birthDate: "1963-08-25",
      deathDate: null,
      currentCity: "Birmingham",
    },
    {
      id: "cur-salma",
      firstName: "Salma",
      lastName: "Rahman",
      gender: "FEMALE" as const,
      birthDate: "1966-03-17",
      deathDate: null,
      currentCity: "Birmingham",
    },
    {
      id: "cur-zara",
      firstName: "Zara",
      lastName: "Hassan",
      gender: "FEMALE" as const,
      birthDate: "2018-09-09",
      deathDate: null,
      currentCity: "London",
    },
    {
      id: "cur-noah",
      firstName: "Noah",
      lastName: "Hassan",
      gender: "MALE" as const,
      birthDate: "2021-02-28",
      deathDate: null,
      currentCity: "London",
    },
  ];

  const unions = [
    {
      id: "cur-u-gp",
      partner1Id: "cur-omar",
      partner2Id: "cur-fatima",
      marriageDate: "1958-12-01",
      divorceDate: null,
      isActive: true,
    },
    {
      id: "cur-u-parents",
      partner1Id: "cur-rashid",
      partner2Id: "cur-nadia",
      marriageDate: "1986-06-14",
      divorceDate: null,
      isActive: true,
    },
    {
      id: "cur-u-kay",
      partner1Id: "cur-kay",
      partner2Id: "cur-aisha",
      marriageDate: "2016-08-20",
      divorceDate: null,
      isActive: true,
    },
    {
      id: "cur-u-aisha-parents",
      partner1Id: "cur-hasan-rahman",
      partner2Id: "cur-salma",
      marriageDate: "1985-04-10",
      divorceDate: null,
      isActive: true,
    },
  ];

  const children = [
    { id: "cur-c-rashid", unionId: "cur-u-gp", childId: "cur-rashid", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-margaret", unionId: "cur-u-gp", childId: "cur-margaret", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-kay", unionId: "cur-u-parents", childId: "cur-kay", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-emma", unionId: "cur-u-parents", childId: "cur-emma", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-ali", unionId: "cur-u-parents", childId: "cur-ali", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-sara", unionId: "cur-u-parents", childId: "cur-sara", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-aisha", unionId: "cur-u-aisha-parents", childId: "cur-aisha", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-yusuf", unionId: "cur-u-aisha-parents", childId: "cur-yusuf", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-zara", unionId: "cur-u-kay", childId: "cur-zara", relationshipType: "BIOLOGICAL" as const },
    { id: "cur-c-noah", unionId: "cur-u-kay", childId: "cur-noah", relationshipType: "BIOLOGICAL" as const },
  ];

  const stats: DemoDatasetStats = {
    persons: persons.length,
    unions: unions.length,
    childLinks: children.length,
    biological: children.length,
    adopted: 0,
    step: 0,
    activeUnions: unions.length,
    remarriages: 0,
    uniqueFullNames: persons.length,
    uniqueCities: new Set(persons.map((p) => p.currentCity)).size,
  };

  return {
    version: 1,
    seed: 42_026_001,
    targetPersons: persons.length,
    focalPersonId: "cur-kay",
    persons,
    unions,
    children,
    stats,
  };
}
